import { Kantumruy_Pro } from "next/font/google";
import Header from "./components/Header";
import Sidebar from "./components/sidebar";
import "./globals.css";

const kantumruyPro = Kantumruy_Pro({
  variable: "--font-kantumruy-pro",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${kantumruyPro.variable} antialiased`}
      >
        <Header />
        <div className="container-geral flex">
          <Sidebar />
          <main className="flex flex-1 items-center justify-center">{children}</main>
        </div>
      </body>
    </html>
  );
}
