import { Montserrat } from "next/font/google";
import Header from "./components/Header";
import Sidebar from "./components/sidebar";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Err2Log",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={`${montserrat.variable} antialiased`}>
        <Header />
        <div className="flex flex-1 h-full relative z-10">
          <Sidebar />
          <main className="flex flex-1 h-full overflow-y-auto items-center md:items-start md:py-6">
            <div className="bg-zinc-200 p-5 rounded-sm mx-auto dark:bg-gray-600 w-5/6 h-fit">
              {children}
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
